"""Tests for hook_installer module.

Note: _sanitize_log_filename is defined in ai_engine.AIEngine but tested here
as requested (it is a static utility method for sanitizing file paths).
"""

import sys
from pathlib import Path
from unittest.mock import patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from commit_ai_guardian.hook_installer import HookInstaller
from commit_ai_guardian.ai_engine import AIEngine


# ---- Fixtures ----

@pytest.fixture
def installer(git_repo):
    """Return a HookInstaller pointing to a temp git repo."""
    return HookInstaller(str(git_repo))


@pytest.fixture
def non_git_path(tmp_path):
    """Return a path that is NOT a git repo."""
    return tmp_path / "not-a-repo"


# ---- HOOK_MARKER ----

class TestHookMarker:
    """Tests for the HOOK_MARKER constant."""

    def test_hook_marker_exists(self):
        """HOOK_MARKER must exist as a class attribute."""
        assert hasattr(HookInstaller, "HOOK_MARKER")

    def test_hook_marker_is_non_empty_string(self):
        """HOOK_MARKER must be a non-empty string."""
        assert isinstance(HookInstaller.HOOK_MARKER, str)
        assert len(HookInstaller.HOOK_MARKER) > 0

    def test_hook_marker_contains_tool_name(self):
        """HOOK_MARKER should contain the tool name for identification."""
        assert "commit-ai-guardian" in HookInstaller.HOOK_MARKER

    def test_hook_marker_starts_with_hash_comment(self):
        """HOOK_MARKER should be a shell comment starting with #."""
        assert HookInstaller.HOOK_MARKER.startswith("#")

    def test_hook_marker_is_consistent(self):
        """HOOK_MARKER value must not change unexpectedly."""
        expected = "# AI Code Review Hook — generated by commit-ai-guardian"
        assert HookInstaller.HOOK_MARKER == expected


# ---- _CONFIG_FIELDS completeness ----

class TestConfigFields:
    """Tests for _CONFIG_FIELDS dictionary completeness."""

    def test_has_fifteen_fields(self):
        """_CONFIG_FIELDS must contain exactly 15 configuration fields."""
        assert len(HookInstaller._CONFIG_FIELDS) == 15

    def test_api_key_field(self):
        """api_key field must have empty-string default and API key comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["api_key"]
        assert default == '""'
        assert "API 密钥" in comment

    def test_api_base_field(self):
        """api_base field must have empty-string default and API address comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["api_base"]
        assert default == '""'
        assert "API" in comment

    def test_model_field(self):
        """model field must have empty-string default and model name comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["model"]
        assert default == '""'
        assert "模型" in comment

    def test_language_field(self):
        """language field must have empty-string default and language comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["language"]
        assert default == '""'
        assert "语言" in comment

    def test_enabled_field(self):
        """enabled field must have 'true' default and enablement comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["enabled"]
        assert default == "true"
        assert "启用" in comment

    def test_severity_threshold_field(self):
        """severity_threshold field must have empty-string default and threshold comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["severity_threshold"]
        assert default == '""'
        assert "阻断" in comment or "级别" in comment

    def test_diff_mode_field(self):
        """diff_mode field must have empty-string default and diff mode comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["diff_mode"]
        assert default == '""'
        assert "diff" in comment or "模式" in comment or "审核" in comment

    def test_max_file_size_field(self):
        """max_file_size field must have '0' default and file size comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["max_file_size"]
        assert default == "0"
        assert "大小" in comment or "KB" in comment

    def test_cache_ttl_field(self):
        """cache_ttl field must have '1d' default and cache TTL comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["cache_ttl"]
        assert default == '"1d"'
        assert "缓存" in comment

    def test_log_ttl_field(self):
        """log_ttl field must have '1h' default and log TTL comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["log_ttl"]
        assert default == '"1h"'
        assert "日志" in comment

    def test_include_patterns_field(self):
        """include_patterns field must have glob-list default and pattern comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["include_patterns"]
        assert default == '["*"]'
        assert "模式" in comment or "glob" in comment or "目录" in comment

    def test_ignore_patterns_field(self):
        """ignore_patterns field must have long glob-list default and ignore comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["ignore_patterns"]
        assert ".lock" in default
        assert "忽略" in comment or "模式" in comment

    def test_timeout_field(self):
        """timeout field must have '0' default and timeout comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["timeout"]
        assert default == "0"
        assert "超时" in comment or "API" in comment

    def test_max_tokens_field(self):
        """max_tokens field must have '0' default and max tokens comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["max_tokens"]
        assert default == "0"
        assert "token" in comment or "长度" in comment or "返回" in comment

    def test_proxy_field(self):
        """proxy field must have empty-string default and proxy comment."""
        default, comment = HookInstaller._CONFIG_FIELDS["proxy"]
        assert default == '""'
        assert "代理" in comment

    def test_each_field_has_tuple_of_length_two(self):
        """Each _CONFIG_FIELDS entry must be a (default, comment) tuple."""
        for key, value in HookInstaller._CONFIG_FIELDS.items():
            assert isinstance(value, tuple), f"{key} value is not a tuple"
            assert len(value) == 2, f"{key} tuple length is not 2"

    def test_each_field_has_non_empty_comment(self):
        """Each _CONFIG_FIELDS entry must have a non-empty comment string."""
        for key, (default, comment) in HookInstaller._CONFIG_FIELDS.items():
            assert isinstance(comment, str) and len(comment) > 0, \
                f"{key} has empty or missing comment"

    def test_each_field_has_string_default(self):
        """Each _CONFIG_FIELDS entry default must be a string."""
        for key, (default, comment) in HookInstaller._CONFIG_FIELDS.items():
            assert isinstance(default, str), f"{key} default is not a string"

    def test_field_names_are_lowercase_with_underscores(self):
        """All field names must use snake_case naming convention."""
        for key in HookInstaller._CONFIG_FIELDS:
            assert key == key.lower(), f"{key} is not lowercase"
            assert " " not in key, f"{key} contains spaces"


# ---- _sanitize_log_filename (from AIEngine) ----

class TestSanitizeLogFilename:
    """Tests for AIEngine._sanitize_log_filename static method.

    This method converts file paths into safe log filenames by:
    - Stripping .ai-review/logs/ and ./ prefixes
    - Replacing path separators and dots with underscores
    """

    def test_plain_relative_path(self):
        """Plain relative path should have separators replaced."""
        result = AIEngine._sanitize_log_filename("src/auth.ts")
        assert result == "src_auth_ts"

    def test_path_with_leading_dot_slash(self):
        """Path starting with ./ should have prefix stripped."""
        result = AIEngine._sanitize_log_filename("./src/auth.ts")
        assert result == "src_auth_ts"

    def test_path_with_ai_review_logs_prefix(self):
        """Path starting with .ai-review/logs/ should have prefix stripped."""
        result = AIEngine._sanitize_log_filename(".ai-review/logs/test.ts")
        assert result == "test_ts"

    def test_single_filename(self):
        """Single filename should have dot replaced."""
        result = AIEngine._sanitize_log_filename("main.py")
        assert result == "main_py"

    def test_empty_string(self):
        """Empty string should return empty string."""
        result = AIEngine._sanitize_log_filename("")
        assert result == ""

    def test_path_with_backslash(self):
        """Windows-style backslash path should be sanitized."""
        result = AIEngine._sanitize_log_filename("src\\auth.ts")
        assert result == "src_auth_ts"

    def test_deeply_nested_path(self):
        """Deeply nested path should have all separators replaced."""
        result = AIEngine._sanitize_log_filename("a/b/c/d/e.py")
        assert result == "a_b_c_d_e_py"

    def test_only_dot_slash_prefix(self):
        """Only ./ prefix should return empty after stripping."""
        result = AIEngine._sanitize_log_filename("./")
        assert result == ""

    def test_both_prefixes_order_matters(self):
        """.ai-review/logs/ prefix should be stripped before ./ prefix check."""
        result = AIEngine._sanitize_log_filename(".ai-review/logs/src/auth.ts")
        # .ai-review/logs/ stripped first → src/auth.ts → src_auth_ts
        assert result == "src_auth_ts"

    def test_does_not_strip_non_prefix_dot_slash(self):
        """./ inside path (not at start) should not be stripped as prefix."""
        result = AIEngine._sanitize_log_filename("src/./auth.ts")
        # ./ is not at the start, so dots and slashes are both replaced with _
        assert result == "src___auth_ts"

    def test_filename_with_multiple_dots(self):
        """Filename with multiple dots should have all dots replaced."""
        result = AIEngine._sanitize_log_filename("some.lib.min.js")
        assert result == "some_lib_min_js"

    def test_root_level_file(self):
        """Root-level file path should be sanitized correctly."""
        result = AIEngine._sanitize_log_filename("Dockerfile")
        assert result == "Dockerfile"  # no dots or slashes

    def test_path_with_leading_slash(self):
        """Absolute Unix path should have leading slash replaced."""
        result = AIEngine._sanitize_log_filename("/home/user/project/main.py")
        # The leading / is replaced with _, then rest follows
        assert "_home_user_project_main_py" in result

    def test_special_chars_preserved_except_separators(self):
        r"""Special characters (other than / \ .) should be preserved."""
        result = AIEngine._sanitize_log_filename("file-name@2x.test.ts")
        assert result == "file-name@2x_test_ts"


# ---- HookInstaller initialization ----

class TestHookInstallerInit:
    """Tests for HookInstaller constructor."""

    def test_init_sets_repo_path(self, git_repo):
        """HookInstaller should store resolved repo path."""
        inst = HookInstaller(str(git_repo))
        assert inst.repo_path == git_repo.resolve()

    def test_init_sets_git_dir(self, installer, git_repo):
        """HookInstaller should set git_dir to .git/ under repo."""
        assert installer.git_dir == git_repo / ".git"

    def test_init_sets_hooks_dir(self, installer, git_repo):
        """HookInstaller should set hooks_dir to .git/hooks/."""
        assert installer.hooks_dir == git_repo / ".git" / "hooks"

    def test_init_sets_hook_path(self, installer, git_repo):
        """HookInstaller should set hook_path to .git/hooks/pre-commit."""
        assert installer.hook_path == git_repo / ".git" / "hooks" / "pre-commit"

    def test_default_repo_path_is_cwd(self):
        """Default repo_path should be current directory."""
        inst = HookInstaller()
        assert inst.repo_path == Path(".").resolve()


# ---- is_git_repo ----

class TestIsGitRepo:
    """Tests for is_git_repo method."""

    def test_returns_true_for_git_repo(self, installer):
        """is_git_repo should return True when .git/ directory exists."""
        assert installer.is_git_repo() is True

    def test_returns_false_for_non_git_repo(self, non_git_path):
        """is_git_repo should return False when .git/ does not exist."""
        non_git_path.mkdir(parents=True)
        inst = HookInstaller(str(non_git_path))
        assert inst.is_git_repo() is False

    def test_returns_false_when_git_is_file_not_dir(self, tmp_path):
        """is_git_repo should return False when .git exists but is a file."""
        (tmp_path / ".git").touch()
        inst = HookInstaller(str(tmp_path))
        assert inst.is_git_repo() is False


# ---- get_hook_path ----

class TestGetHookPath:
    """Tests for get_hook_path method."""

    def test_returns_string(self, installer):
        """get_hook_path should return a string."""
        path = installer.get_hook_path()
        assert isinstance(path, str)

    def test_returns_pre_commit_path(self, installer, git_repo):
        """get_hook_path should return path to pre-commit hook."""
        path = installer.get_hook_path()
        expected = str((git_repo / ".git" / "hooks" / "pre-commit").resolve())
        assert path == expected


# ---- is_hook_installed ----

class TestIsHookInstalled:
    """Tests for is_hook_installed method."""

    def test_returns_false_when_hook_missing(self, installer):
        """is_hook_installed should return False when pre-commit does not exist."""
        assert installer.is_hook_installed() is False

    def test_returns_true_when_marker_present(self, installer):
        """is_hook_installed should return True when file contains HOOK_MARKER."""
        installer.hooks_dir.mkdir(parents=True, exist_ok=True)
        installer.hook_path.write_text(
            HookInstaller.HOOK_MARKER + "\n#!/bin/bash\n", encoding="utf-8"
        )
        assert installer.is_hook_installed() is True

    def test_returns_false_when_marker_absent(self, installer):
        """is_hook_installed should return False when file lacks HOOK_MARKER."""
        installer.hooks_dir.mkdir(parents=True, exist_ok=True)
        installer.hook_path.write_text("#!/bin/bash\necho hello\n", encoding="utf-8")
        assert installer.is_hook_installed() is False

    def test_returns_false_when_hook_is_binary(self, installer):
        """is_hook_installed should return False when file cannot be decoded as text."""
        installer.hooks_dir.mkdir(parents=True, exist_ok=True)
        installer.hook_path.write_bytes(b"\x00\x01\x02\xff\xfe")
        assert installer.is_hook_installed() is False

    def test_returns_false_on_os_error(self, installer):
        """is_hook_installed should return False on OSError during read."""
        installer.hooks_dir.mkdir(parents=True, exist_ok=True)
        installer.hook_path.write_text(HookInstaller.HOOK_MARKER, encoding="utf-8")
        # Make hooks_dir unreadable to cause OSError
        with patch.object(Path, "read_text", side_effect=OSError("permission denied")):
            # Use a fresh installer to trigger the read
            assert installer.is_hook_installed() is False
