"""Git Hook 安装器

负责在目标仓库的 .git/hooks/pre-commit 位置写入/删除 hook 脚本。

安全机制：
- 通过 HOOK_MARKER 识别"本工具生成的 hook" vs "用户自定义的 hook"
- 覆盖用户 hook 前自动备份为 .backup
- 卸载时自动恢复备份
"""

import os
import shutil
import stat
from pathlib import Path
from typing import Optional


class HookInstaller:
    """Git pre-commit hook 安装管理器
    
    操作路径：<repo>/.git/hooks/pre-commit
    
    三种场景的处理：
    1. 没有 pre-commit → 直接创建
    2. 有 pre-commit，且包含 HOOK_MARKER → 直接覆盖（是我们之前装的）
    3. 有 pre-commit，但没有 HOOK_MARKER → 拒绝操作（保护用户自定义 hook）
    """
    
    # 这个标记写在 hook 脚本的第一行注释里，用于识别"本工具生成的 hook"
    HOOK_MARKER = "# AI Code Review Hook — generated by commit-ai-guardian"
    
    def __init__(self, repo_path: str = "."):
        """初始化
        
        Args:
            repo_path: Git 仓库路径，默认当前目录
        """
        self.repo_path = Path(repo_path).resolve()
        self.git_dir = self.repo_path / ".git"           # .git 目录
        self.hooks_dir = self.git_dir / "hooks"          # hooks 目录
        self.hook_path = self.hooks_dir / "pre-commit"   # pre-commit 文件路径
    
    def is_git_repo(self) -> bool:
        """检查目标路径是否为 Git 仓库（判断依据：有没有 .git/ 目录）"""
        return self.git_dir.is_dir()
    
    def get_hook_path(self) -> str:
        """获取 pre-commit hook 的绝对路径"""
        return str(self.hook_path)
    
    def is_hook_installed(self) -> bool:
        """检查 pre-commit hook 是否已由本工具安装
        
        判断逻辑：文件存在 且 内容包含 HOOK_MARKER
        
        Returns:
            True = 是本工具安装的，可以安全覆盖/卸载
            False = 不存在 或 是其他工具/用户自定义的
        """
        if not self.hook_path.exists():
            return False
        try:
            content = self.hook_path.read_text(encoding='utf-8')
            return self.HOOK_MARKER in content
        except (OSError, UnicodeDecodeError):
            return False
    
    def install(self, force: bool = False) -> bool:
        """安装 pre-commit hook
        
        执行流程：
        1. 检查是否为 Git 仓库
        2. 如果已有用户自定义 hook → 拒绝（或 --force 备份后覆盖）
        3. 从模板读取脚本内容，写入 .git/hooks/pre-commit
        4. chmod +x 赋予执行权限
        
        Args:
            force: True = 强制覆盖已有 hook（会自动备份）
            
        Returns:
            True = 安装成功
            False = 安装失败（如已有用户 hook 且未加 --force）
            
        Raises:
            RuntimeError: 目标路径不是 Git 仓库
        """
        if not self.is_git_repo():
            raise RuntimeError(f"'{self.repo_path}' 不是 Git 仓库")
        
        # 确保 hooks 目录存在（mkdir -p 的效果）
        self.hooks_dir.mkdir(parents=True, exist_ok=True)
        
        # 场景 3：已有用户自定义 hook（不含 HOOK_MARKER）
        if self.hook_path.exists() and not self.is_hook_installed():
            if not force:
                # 不加 --force：拒绝操作，保护用户配置
                print(f"[警告] 已存在自定义 pre-commit hook")
                print(f"        路径: {self.hook_path}")
                print(f"        使用 --force 覆盖，或先手动备份")
                return False
            # 加 --force：备份原 hook，然后覆盖
            backup_path = self.hook_path.with_suffix('.backup')
            shutil.copy2(self.hook_path, backup_path)
            print(f"[信息] 原 hook 已备份到: {backup_path}")
        
        # 写入脚本（从模板文件读取，或返回内置默认脚本）
        hook_script = self._get_hook_script()
        self.hook_path.write_text(hook_script, encoding='utf-8')
        
        # Git 要求 hook 必须有执行权限，否则 commit 时会报错 "permission denied"
        self.hook_path.chmod(self.hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        
        print(f"[成功] pre-commit hook 已安装到: {self.hook_path}")
        
        # 安装 hook 时顺便初始化 .ai-review/ 案例目录
        self._init_review_dir()
        
        return True
    
    def uninstall(self) -> bool:
        """卸载 pre-commit hook
        
        执行流程：
        1. 如果 hook 不存在 → 无需操作
        2. 如果 hook 不是本工具生成的 → 拒绝删除（保护用户配置）
        3. 删除 hook 文件，如果有 .backup 则恢复
        
        Returns:
            True = 卸载成功（或无需卸载）
            False = 卸载失败（如不是本工具生成的 hook）
        """
        # 场景 1：没有 hook
        if not self.hook_path.exists():
            print("[信息] 没有找到 pre-commit hook，无需卸载")
            return True
        
        # 场景 3：用户自定义 hook → 不碰
        if not self.is_hook_installed():
            print("[警告] pre-commit hook 不是由本工具生成的，不会自动卸载")
            print(f"        如需手动删除，请执行: rm {self.hook_path}")
            return False
        
        # 场景 2：本工具生成的 → 删除，并恢复备份（如果有）
        try:
            self.hook_path.unlink()  # 删除文件
            print("[成功] pre-commit hook 已卸载")
            
            # 卸载时恢复之前备份的自定义 hook（如果存在）
            backup_path = self.hook_path.with_suffix('.backup')
            if backup_path.exists():
                shutil.move(backup_path, self.hook_path)
                print(f"[信息] 原 hook 已从备份恢复")
            
            return True
        except OSError as e:
            print(f"[错误] 卸载失败: {e}")
            return False
    
    def _init_review_dir(self) -> bool:
        """在目标仓库初始化 .ai-review/ 项目配置目录（install 时自动调用）
        
        创建 .ai-review/cases/ 目录，并复制示例案例文件。
        用户可以根据项目需求修改这些示例。
        
        Returns:
            True = 初始化成功（或已存在）
            False = 失败
        """
        if not self.is_git_repo():
            print(f"[错误] '{self.repo_path}' 不是 Git 仓库")
            return False
        
        # 创建 .ai-review/ 下的目录结构
        review_dir = self.repo_path / ".ai-review"
        cases_dir = review_dir / "cases"      # ← 用户把需要启用的案例放这里
        example_dir = review_dir / "example"  # ← 工具自带的示例模板放这里
        
        try:
            # 创建 cases/（空目录，用户自己添加案例）
            cases_dir.mkdir(parents=True, exist_ok=True)
            
            # 创建 example/（放示例模板，不参与审核）
            is_new_example = not example_dir.exists()
            example_dir.mkdir(parents=True, exist_ok=True)
            
            # 复制示例案例文件到 example/（不复制到 cases/）
            examples_source = Path(__file__).parent / "templates" / "case-examples"
            copied = 0
            if examples_source.exists():
                for example_file in sorted(examples_source.glob("*.yaml")):
                    target = example_dir / example_file.name
                    if not target.exists():
                        import shutil
                        shutil.copy2(example_file, target)
                        copied += 1
            
            # 只在第一次创建时打印提示
            if is_new_example:
                print(f"\n[信息] 案例目录已初始化: {review_dir}")
                if copied > 0:
                    print(f"        {copied} 个示例模板已放到 example/（不参与审核）")
                print(f"        启用案例: 从 example/ 复制 .yaml 文件到 cases/")
                print(f"        共享给团队: git add .ai-review/ && git commit")
            return True
            
        except OSError as e:
            print(f"[错误] 初始化失败: {e}")
            return False

    def _get_hook_script(self) -> str:
        """获取 hook 脚本内容
        
        优先从 templates/pre-commit-hook-template 文件读取。
        如果模板文件丢失（比如被误删），返回内置的默认脚本作为兜底。
        
        Path(__file__).parent = 当前 Python 文件所在的目录
        拼接 /templates/pre-commit-hook-template 得到模板文件的绝对路径
        """
        template_path = Path(__file__).parent / "templates" / "pre-commit-hook-template"
        if template_path.exists():
            return template_path.read_text(encoding='utf-8')
        
        # 模板文件不存在时的兜底方案（理论上不会发生）
        return '''#!/bin/bash
# AI Code Review Hook — generated by commit-ai-guardian
# 此文件由工具自动生成，请勿手动修改

# 获取脚本所在目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# 检测 uv 是否可用，优先使用 uv run
if command -v uv &> /dev/null; then
    uv run --python-preference only-managed python -m commit_ai_guardian audit --repo "$REPO_ROOT"
else
    python -m commit_ai_guardian audit --repo "$REPO_ROOT"
fi

# 获取退出码
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo ""
    echo "提示: 使用 git commit --no-verify 跳过 AI 审核（不推荐）"
    exit $EXIT_CODE
fi

exit 0
'''
