"""Git Hook 安装器 - 负责在 Git 仓库中安装和卸载 pre-commit hook."""

import os
import shutil
import stat
from pathlib import Path
from typing import Optional


class HookInstaller:
    """Git pre-commit hook 安装管理器"""
    
    HOOK_MARKER = "# AI Code Review Hook — generated by commit-ai-guardian"
    
    def __init__(self, repo_path: str = "."):
        """
        初始化 Hook 安装器
        
        Args:
            repo_path: Git 仓库路径，默认为当前目录
        """
        self.repo_path = Path(repo_path).resolve()
        self.git_dir = self.repo_path / ".git"
        self.hooks_dir = self.git_dir / "hooks"
        self.hook_path = self.hooks_dir / "pre-commit"
    
    def is_git_repo(self) -> bool:
        """检查目标路径是否为 Git 仓库"""
        return self.git_dir.is_dir()
    
    def get_hook_path(self) -> str:
        """获取 pre-commit hook 的完整路径"""
        return str(self.hook_path)
    
    def is_hook_installed(self) -> bool:
        """
        检查 pre-commit hook 是否已由本工具安装
        
        Returns:
            True 如果 hook 已安装且包含本工具的标记
        """
        if not self.hook_path.exists():
            return False
        try:
            content = self.hook_path.read_text(encoding='utf-8')
            return self.HOOK_MARKER in content
        except (OSError, UnicodeDecodeError):
            return False
    
    def install(self, force: bool = False) -> bool:
        """
        安装 pre-commit hook
        
        Args:
            force: 是否强制覆盖已存在的 hook
            
        Returns:
            安装是否成功
            
        Raises:
            RuntimeError: 如果不是 Git 仓库
        """
        if not self.is_git_repo():
            raise RuntimeError(f"'{self.repo_path}' 不是 Git 仓库")
        
        self.hooks_dir.mkdir(parents=True, exist_ok=True)
        
        # 如果 hook 已存在且不是本工具生成的，备份它
        if self.hook_path.exists() and not self.is_hook_installed():
            if not force:
                print(f"[警告] 已存在自定义 pre-commit hook")
                print(f"        路径: {self.hook_path}")
                print(f"        使用 --force 覆盖，或先手动备份")
                return False
            # 备份原 hook
            backup_path = self.hook_path.with_suffix('.backup')
            shutil.copy2(self.hook_path, backup_path)
            print(f"[信息] 原 hook 已备份到: {backup_path}")
        
        # 写入 hook 脚本（替换模板中的占位符）
        hook_script = self._get_hook_script()
        self.hook_path.write_text(hook_script, encoding='utf-8')
        
        # 赋予执行权限
        self.hook_path.chmod(self.hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        
        print(f"[成功] pre-commit hook 已安装到: {self.hook_path}")
        return True
    
    def uninstall(self) -> bool:
        """
        卸载 pre-commit hook
        
        Returns:
            卸载是否成功
        """
        if not self.hook_path.exists():
            print("[信息] 没有找到 pre-commit hook，无需卸载")
            return True
        
        if not self.is_hook_installed():
            print("[警告] pre-commit hook 不是由本工具生成的，不会自动卸载")
            print(f"        如需手动删除，请执行: rm {self.hook_path}")
            return False
        
        try:
            self.hook_path.unlink()
            print("[成功] pre-commit hook 已卸载")
            
            # 如果存在备份，恢复备份
            backup_path = self.hook_path.with_suffix('.backup')
            if backup_path.exists():
                shutil.move(backup_path, self.hook_path)
                print(f"[信息] 原 hook 已从备份恢复")
            
            return True
        except OSError as e:
            print(f"[错误] 卸载失败: {e}")
            return False
    
    def _get_hook_script(self) -> str:
        """获取 hook 脚本内容"""
        template_path = Path(__file__).parent / "templates" / "pre-commit-hook-template"
        if template_path.exists():
            return template_path.read_text(encoding='utf-8')
        
        # 如果模板文件不存在，返回默认脚本（优先使用 uv）
        return '''#!/bin/bash
# AI Code Review Hook — generated by commit-ai-guardian
# 此文件由工具自动生成，请勿手动修改

# 获取脚本所在目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# 检测 uv 是否可用，优先使用 uv run
if command -v uv &> /dev/null; then
    uv run --python-preference only-managed python -m commit_ai_guardian audit --repo "$REPO_ROOT"
else
    python -m commit_ai_guardian audit --repo "$REPO_ROOT"
fi

# 获取退出码
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo ""
    echo "提示: 使用 git commit --no-verify 跳过 AI 审核（不推荐）"
    exit $EXIT_CODE
fi

exit 0
'''
