"""Git Hook 安装器

负责在目标仓库的 .git/hooks/pre-commit 位置写入/删除 hook 脚本。

安全机制：
- 通过 HOOK_MARKER 识别"本工具生成的 hook" vs "用户自定义的 hook"
- 覆盖用户 hook 前自动备份为 .backup
- 卸载时自动恢复备份
"""

import os
import shutil
import stat
from pathlib import Path
from typing import Optional


class HookInstaller:
    """Git pre-commit hook 安装管理器
    
    操作路径：<repo>/.git/hooks/pre-commit
    
    三种场景的处理：
    1. 没有 pre-commit → 直接创建
    2. 有 pre-commit，且包含 HOOK_MARKER → 直接覆盖（是我们之前装的）
    3. 有 pre-commit，但没有 HOOK_MARKER → 拒绝操作（保护用户自定义 hook）
    """
    
    # 这个标记写在 hook 脚本的第一行注释里，用于识别"本工具生成的 hook"
    HOOK_MARKER = "# AI Code Review Hook — generated by commit-ai-guardian"
    
    def __init__(self, repo_path: str = "."):
        """初始化
        
        Args:
            repo_path: Git 仓库路径，默认当前目录
        """
        self.repo_path = Path(repo_path).resolve()
        self.git_dir = self.repo_path / ".git"           # .git 目录
        self.hooks_dir = self.git_dir / "hooks"          # hooks 目录
        self.hook_path = self.hooks_dir / "pre-commit"   # pre-commit 文件路径
    
    def is_git_repo(self) -> bool:
        """检查目标路径是否为 Git 仓库（判断依据：有没有 .git/ 目录）"""
        return self.git_dir.is_dir()
    
    def get_hook_path(self) -> str:
        """获取 pre-commit hook 的绝对路径"""
        return str(self.hook_path)
    
    def is_hook_installed(self) -> bool:
        """检查 pre-commit hook 是否已由本工具安装
        
        判断逻辑：文件存在 且 内容包含 HOOK_MARKER
        
        Returns:
            True = 是本工具安装的，可以安全覆盖/卸载
            False = 不存在 或 是其他工具/用户自定义的
        """
        if not self.hook_path.exists():
            return False
        try:
            content = self.hook_path.read_text(encoding='utf-8')
            return self.HOOK_MARKER in content
        except (OSError, UnicodeDecodeError):
            return False
    
    def install(self, force: bool = False) -> bool:
        """安装 pre-commit hook
        
        执行流程：
        1. 检查是否为 Git 仓库
        2. 如果已有用户自定义 hook → 拒绝（或 --force 备份后覆盖）
        3. 从模板读取脚本内容，写入 .git/hooks/pre-commit
        4. chmod +x 赋予执行权限
        
        Args:
            force: True = 强制覆盖已有 hook（会自动备份）
            
        Returns:
            True = 安装成功
            False = 安装失败（如已有用户 hook 且未加 --force）
            
        Raises:
            RuntimeError: 目标路径不是 Git 仓库
        """
        if not self.is_git_repo():
            raise RuntimeError(f"'{self.repo_path}' 不是 Git 仓库")
        
        # 确保 hooks 目录存在（mkdir -p 的效果）
        self.hooks_dir.mkdir(parents=True, exist_ok=True)
        
        # 场景 3：已有用户自定义 hook（不含 HOOK_MARKER）
        if self.hook_path.exists() and not self.is_hook_installed():
            if not force:
                # 不加 --force：拒绝操作，保护用户配置
                print(f"[警告] 已存在自定义 pre-commit hook")
                print(f"        路径: {self.hook_path}")
                print(f"        使用 --force 覆盖，或先手动备份")
                return False
            # 加 --force：备份原 hook，然后覆盖
            backup_path = self.hook_path.with_suffix('.backup')
            shutil.copy2(self.hook_path, backup_path)
            print(f"[信息] 原 hook 已备份到: {backup_path}")
        
        # 写入脚本（从模板文件读取，或返回内置默认脚本）
        hook_script = self._get_hook_script()
        self.hook_path.write_text(hook_script, encoding='utf-8')
        
        # Git 要求 hook 必须有执行权限，否则 commit 时会报错 "permission denied"
        self.hook_path.chmod(self.hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        
        print(f"[成功] pre-commit hook 已安装到: {self.hook_path}")
        
        # 安装 hook 时顺便初始化 .ai-review/ 案例目录
        self._init_review_dir(force=force)
        
        return True
    
    def uninstall(self) -> bool:
        """卸载 pre-commit hook
        
        执行流程：
        1. 如果 hook 不存在 → 无需操作
        2. 如果 hook 不是本工具生成的 → 拒绝删除（保护用户配置）
        3. 删除 hook 文件，如果有 .backup 则恢复
        
        Returns:
            True = 卸载成功（或无需卸载）
            False = 卸载失败（如不是本工具生成的 hook）
        """
        # 场景 1：没有 hook
        if not self.hook_path.exists():
            print("[信息] 没有找到 pre-commit hook，无需卸载")
            return True
        
        # 场景 3：用户自定义 hook → 不碰
        if not self.is_hook_installed():
            print("[警告] pre-commit hook 不是由本工具生成的，不会自动卸载")
            print(f"        如需手动删除，请执行: rm {self.hook_path}")
            return False
        
        # 场景 2：本工具生成的 → 删除，并恢复备份（如果有）
        try:
            self.hook_path.unlink()  # 删除文件
            print("[成功] pre-commit hook 已卸载")
            
            # 卸载时恢复之前备份的自定义 hook（如果存在）
            backup_path = self.hook_path.with_suffix('.backup')
            if backup_path.exists():
                shutil.move(backup_path, self.hook_path)
                print(f"[信息] 原 hook 已从备份恢复")
            
            return True
        except OSError as e:
            print(f"[错误] 卸载失败: {e}")
            return False
    
    def _init_review_dir(self, force: bool = False) -> bool:
        """在目标仓库初始化 .ai-review/ 项目配置目录（install 时自动调用）
        
        创建 .ai-review/cases/ 目录，并复制示例案例文件。
        用户可以根据项目需求修改这些示例。
        
        Returns:
            True = 初始化成功（或已存在）
            False = 失败
        """
        if not self.is_git_repo():
            print(f"[错误] '{self.repo_path}' 不是 Git 仓库")
            return False
        
        # 创建 .ai-review/ 下的目录结构
        review_dir = self.repo_path / ".ai-review"
        cases_dir = review_dir / "cases"      # ← 用户把需要启用的案例放这里
        example_dir = review_dir / "example"  # ← 工具自带的示例模板放这里
        prompts_dir = review_dir / "prompts"  # ← prompt 模板（用户可以自定义审核行为）
        cache_dir = review_dir / "cache"      # ← 审核结果缓存（MD5 → 结果）
        logs_dir = review_dir / "logs"        # ← 审核日志（prompt/ai 响应）
        
        try:
            # 创建 cases/（空目录，用户自己添加案例）
            cases_dir.mkdir(parents=True, exist_ok=True)
            
            # 创建 example/（放示例模板，不参与审核）
            is_new_example = not example_dir.exists()
            example_dir.mkdir(parents=True, exist_ok=True)
            
            # 创建 prompts/（放 prompt 模板，install 时写入默认模板）
            prompts_dir.mkdir(parents=True, exist_ok=True)
            
            # 创建 cache/（审核结果缓存，MD5 → 结果）
            cache_dir.mkdir(parents=True, exist_ok=True)
            
            # 创建 logs/（审核日志目录：{filename}.prompt.log / {filename}.ai.log）
            logs_dir.mkdir(parents=True, exist_ok=True)
            
            # 创建 .ai-review/.gitignore（忽略自动生成的 cache/ 和 logs/）
            gitignore_file = review_dir / ".gitignore"
            if not gitignore_file.exists():
                gitignore_file.write_text(
                    "# 自动生成的文件，不需要提交到 Git\n"
                    "cache/\n"
                    "logs/\n",
                    encoding='utf-8'
                )
            
            # 复制示例案例文件到 example/（Markdown 格式，.md）
            examples_source = Path(__file__).parent / "templates" / "case-examples"
            copied = 0
            if examples_source.exists():
                for example_file in sorted(examples_source.glob("*.md")):
                    target = example_dir / example_file.name
                    if not target.exists():
                        import shutil
                        shutil.copy2(example_file, target)
                        copied += 1
            
            # 写入默认 prompt 模板（用户可以修改来自定义审核行为）
            from .prompt_loader import PromptLoader
            template_files = PromptLoader.get_default_template_files()
            for template_name, template_content in template_files.items():
                template_path = prompts_dir / template_name
                if not template_path.exists() or force:
                    template_path.write_text(template_content, encoding='utf-8')
                    if force and template_path.exists():
                        print(f"[信息] prompt 模板已更新: {template_name}")
            
            # 创建用户自定义 prompt 文件（custom_prompt.md）
            # 此文件不会被 install --force 覆盖，用户可在此添加自己的审核规则
            custom_prompt_path = prompts_dir / "custom_prompt.md"
            if not custom_prompt_path.exists():
                custom_prompt_path.write_text(
                    "<!-- 自定义审核规则 -->\n"
                    "<!-- 此文件内容会在每次审核前作为 system message 的一部分发送给 AI -->\n"
                    "<!-- 可以在此添加团队特定的编码规范、业务规则等 -->\n"
                    "\n"
                    "## 团队自定义规则\n"
                    "\n"
                    "在此添加你的自定义审核规则...\n",
                    encoding='utf-8'
                )
                print(f"[信息] 自定义 prompt 模板已创建: custom_prompt.md（不会被覆盖）")
            
            # 创建或补全项目配置文件 config.yaml
            self._ensure_config_file(review_dir / "config.yaml")
            
            # 只在第一次创建时打印提示
            if is_new_example:
                print(f"\n[信息] 案例目录已初始化: {review_dir}")
                if copied > 0:
                    print(f"        {copied} 个示例模板已放到 example/（不参与审核）")
                print(f"        启用案例: 从 example/ 复制 .yaml 文件到 cases/")
                print(f"        共享给团队: git add .ai-review/ && git commit")
            return True
            
        except OSError as e:
            print(f"[错误] 初始化失败: {e}")
            return False
    
    # config.yaml 的完整字段定义（key: (默认值, 注释)）
    _CONFIG_FIELDS = {
        'api_key': ('""', 'AI API 密钥'),
        'api_base': ('""', 'API 地址'),
        'model': ('""', '模型名称'),
        'language': ('""', '审核报告语言 (zh-CN/en)'),
        'enabled': ('true', '是否启用 AI 审核（false=跳过，直接通过）'),
        'severity_threshold': ('""', '阻断级别 (info/warning/error/critical)'),
        'diff_mode': ('""', 'diff 审核模式: full=完整文件(默认), diff=只审变更'),
        'max_file_size': ('0', '最大审核文件大小 (KB)'),
        'cache_ttl': ('"1d"', '缓存存活时间（1d=1天, 12h=12小时, 30m=30分钟）'),
        'log_ttl': ('"1h"', '日志存活时间（1h=1小时, 30m=30分钟, 0=不清理）'),
        'include_patterns': ('["*"]', '要审核的目录/文件模式（glob，如 ["src/**", "app/**"]）'),
        'ignore_patterns': (r'["*.lock", "*.md", "*.txt", "*.svg", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.ico", "*.woff", "*.woff2", "*.ttf", "*.eot", "*.otf", "*.mp3", "*.mp4", "*.avi", "*.pdf", "*.doc", "*.docx", "*.zip", "*.tar", "*.gz", "*.rar", "*.7z", "*.exe", "*.dll", "*.so", "*.dylib", "*.class", "*.jar", "*.ear", "*.egg", "*.whl", "*.parquet", "*.pkl", "*.pickle", "*.model", "*.bin", "*.onnx", "*.pb"]', '忽略的文件模式（glob 格式）'),
        'case_format': ('"default"', '案例格式化级别: default=全部(默认), compact=精简, minimal=最小'),
        'timeout': ('0', 'API 超时 (秒)'),
        'max_tokens': ('0', 'AI 最大返回长度 (token 数，支持 4K/8K 写法)'),
        'proxy': ('""', 'HTTP 代理地址'),
    }
    
    def _ensure_config_file(self, config_file: Path) -> None:
        """确保 config.yaml 存在且包含所有字段
        
        - 文件不存在：创建完整的新文件
        - 文件存在：读取现有内容，补全缺失的字段
        
        Args:
            config_file: config.yaml 的路径
        """
        try:
            if config_file.exists():
                # 文件已存在，读取并补全缺失字段
                existing = config_file.read_text(encoding='utf-8')
                
                try:
                    import yaml
                    data = yaml.safe_load(existing) or {}
                except Exception:
                    data = {}
                
                # 找出缺失的字段
                missing = []
                for key, (default, comment) in self._CONFIG_FIELDS.items():
                    if key not in data:
                        missing.append((key, default, comment))
                
                if missing:
                    # 追加缺失字段到文件
                    lines = ["\n# === 以下字段由 install --force 自动补全 ===\n"]
                    for key, default, comment in missing:
                        lines.append(f"\n# {comment}\n{key}: {default}\n")
                    
                    config_file.write_text(existing + "\n".join(lines), encoding='utf-8')
                    print(f"[信息] config.yaml 已补全 {len(missing)} 个缺失字段")
            else:
                # 文件不存在，创建完整的新文件
                lines = [
                    "# 项目级别配置文件\n",
                    "# 只填写需要覆盖全局配置的项，留空则使用全局配置\n",
                    "# 全局配置位置: ~/.commit-ai-guardian/config.yaml\n",
                ]
                for key, (default, comment) in self._CONFIG_FIELDS.items():
                    lines.append(f"\n# {comment}\n{key}: {default}\n")
                
                config_file.write_text("".join(lines), encoding='utf-8')
        
        except OSError as e:
            print(f"[警告] config.yaml 处理失败: {e}")

    def _get_hook_script(self) -> str:
        """获取 hook 脚本内容
        
        优先从 templates/pre-commit-hook-template 文件读取。
        如果模板文件丢失（比如被误删），返回内置的默认脚本作为兜底。
        
        Path(__file__).parent = 当前 Python 文件所在的目录
        拼接 /templates/pre-commit-hook-template 得到模板文件的绝对路径
        """
        template_path = Path(__file__).parent / "templates" / "pre-commit-hook-template"
        if template_path.exists():
            return template_path.read_text(encoding='utf-8')
        
        # 模板文件不存在时的兜底方案（理论上不会发生）
        return '''#!/bin/bash
# AI Code Review Hook — generated by commit-ai-guardian
# 此文件由工具自动生成，请勿手动修改

# 获取脚本所在目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# 跳过 merge/rebase 操作（别人的代码不审核）
if [ -f "$REPO_ROOT/.git/MERGE_HEAD" ]; then
    echo "[信息] 处于 merge 状态，跳过 AI 审核"
    exit 0
fi
if [ -d "$REPO_ROOT/.git/rebase-merge" ] || [ -d "$REPO_ROOT/.git/rebase-apply" ]; then
    echo "[信息] 处于 rebase 状态，跳过 AI 审核"
    exit 0
fi

# 直接调用 commit-ai-guardian 命令（通过 uv tool install 已加入 PATH）
# 不用 'python -m' 或 'uv run'，避免目标仓库的 Python 环境问题
commit-ai-guardian audit --repo "$REPO_ROOT"

# 获取退出码
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo ""
    echo "提示: 使用 git commit --no-verify 跳过 AI 审核（不推荐）"
    exit $EXIT_CODE
fi

exit 0
'''
